name: Clang-tidy

on: [ push ]

jobs:
  Clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo scripts/setup_dev_env.bash ubuntu

      - name: Run clang-tidy
        run: |
          scripts/run_clang_tidy.bash

      - name: Upload clang-tidy report
        uses: actions/upload-artifact@v4
        if : always()
        with:
          name: clang-tidy-report
          path: reports/clang-tidy-report.txt
