name: Cppcheck

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo scripts/setup_dev_env.bash ubuntu

      - name: Run cppcheck
        run: |
          scripts/run_cppcheck.bash

      - name: Upload cppcheck report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cppcheck-report
          path: reports/cppcheck-output.txt
