name: Linux tests

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo scripts/setup_dev_env.bash ubuntu

      - name: Run tests
        run: sudo scripts/build_and_run_unit_tests.bash
